### PR TITLE
Remove unused gleam_http

### PR DESCRIPTION
**Pull request by greenfork**

### CODE REVIEW

**Comment by greenfork** [comment]
CI seems to fail because it has incorrect settings

**Comment by rawhat** [comment]
Huh I swear I left a comment on this yesterday.  Sorry about that!  I updated the workflow and I think this should be good to go now.  Should just need to rebase this off of those changes.

**Comment by greenfork** [comment]
Right, seems to work, rebased.

**Comment by rawhat** [comment]
Thank you!

**Pull request merged**
